name: CI/CD__DEV

on:
  push:
    branches:
      - develop

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    needs: CI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup EAS CLI and login
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.TOKEN_LOGIN_EAS }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Push SECRETS_CLIENT_APP_TELECOM_API_AUTH to Expo EAS
        run: eas env:create --name EXPO_PUBLIC_CLIENT_APP_TELECOM_API_AUTH --value "${{ secrets.SECRETS_CLIENT_APP_TELECOM_API_AUTH }}" --visibility=plaintext --environment=preview --non-interactive

      - name: Push SECRETS_CLIENT_APP_TELECOM_API_TOKEN to Expo EAS
        run: eas env:create --name EXPO_PUBLIC_CLIENT_APP_TELECOM_API_TOKEN --value "${{ secrets.SECRETS_CLIENT_APP_TELECOM_API_TOKEN }}" --visibility=plaintext --environment=preview --non-interactive

      - name: Push SECRETS_CLIENT_APP_TELECOM_CLIENT_ID to Expo EAS
        run: eas env:create --name EXPO_PUBLIC_CLIENT_APP_TELECOM_CLIENT_ID --value "${{ secrets.SECRETS_CLIENT_APP_TELECOM_CLIENT_ID }}" --visibility=plaintext --environment=preview --non-interactive

      - name: Push SECRETS_CLIENT_APP_TELECOM_CLIENT_SECRET to Expo EAS
        run: eas env:create --name EXPO_PUBLIC_CLIENT_APP_TELECOM_CLIENT_SECRET --value "${{ secrets.SECRETS_CLIENT_APP_TELECOM_CLIENT_SECRET }}" --visibility=plaintext --environment=preview --non-interactive

      - name: Run EAS Build
        run: eas build --platform android --profile preview --non-interactive --no-wait
